# EduLift Mobile - Analysis Options

linter:
  rules:
    # Security Rules (Critical for Mobile)
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    
    # Accessibility Rules (WCAG 2.1 AA Compliance)
    use_build_context_synchronously: true
    
    # Performance Rules
    prefer_const_declarations: true
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    
    # Code Quality Rules
    always_declare_return_types: true
    always_specify_types: false  # Let type inference work
    annotate_overrides: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    omit_local_variable_types: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    valid_regexps: true
    
    # Flutter specific rules
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true
    use_full_hex_values_for_flutter_colors: true
    prefer_const_constructors_in_immutables: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/firebase_options.dart"
    - "test/unit/data/family/repositories/family_repository_extractor_integration_test.dart"  # Obsolete test - methods removed from interface
    - "test/unit/core/router/app_router_redirect_test.dart"  # Obsolete - tests User.familyId architecture
    - "test/unit/core/router/authenticated_without_family_redirect_test.dart"  # Obsolete User.familyId
    - "test/unit/core/router/family_redirect_bug_fix_test.dart"  # Obsolete User.familyId
    - "test/unit/core/router/family_redirect_regression_test.dart"  # Obsolete User.familyId
    - "test/unit/core/router/router_refresh_isolation_test.dart"  # Obsolete User.familyId
    - "test/unit/core/router/router_refresh_notifier_test.dart"  # Obsolete User.familyId
  
  plugins:
    - dart_code_metrics
    # Temporarily disabled custom_lint due to unrecognized error codes
    # - custom_lint
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    # Security-critical errors
    avoid_print: error
    avoid_web_libraries_in_flutter: error

    # Accessibility-critical errors
    use_build_context_synchronously: error

    # Performance-critical errors
    avoid_function_literals_in_foreach_calls: warning

    # Code quality errors
    always_declare_return_types: error
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning

    # Freezed/JsonSerializable compatibility (2025 best practice)
    # JsonKey annotations on Freezed factory parameters are valid but trigger false positives
    invalid_annotation_target: ignore
    
    # Custom lint rules temporarily disabled due to compilation errors
    # either_pattern_detected: warning
    # enforce_result_pattern: info
    # migration_progress_tracker: error
    # fold_method_detected: info

# Dart Code Metrics Configuration
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    
  metrics-exclude:
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
  rules:
    # Security Rules
    - avoid-late-keyword:
        severity: warning
    - avoid-global-state:
        severity: error
    - avoid-unused-parameters:
        severity: warning
    - prefer-trailing-comma:
        severity: style
    - prefer-conditional-expressions:
        severity: style
    - no-boolean-literal-compare:
        severity: style
    - no-empty-block:
        severity: warning
    - prefer-moving-to-variable:
        severity: style
    - prefer-match-file-name:
        severity: warning
        
  rules-exclude:
    - test/**

# Custom lint configuration for Result pattern enforcement - DISABLED
# Temporarily disabled due to missing result_pattern_lints package
# custom_lint:
#   rules:
#     # Either pattern detection and migration tracking
#     either_pattern_detected:
#       severity: warning
#       exclude:
#         # Allow Either in pattern adapter files during transition
#         - "lib/core/utils/pattern_adapters.dart"
#         # Allow in test files for backward compatibility testing
#         - "test/**"
#     
#     # Result pattern enforcement in new development
#     enforce_result_pattern:
#       severity: info
#       include:
#         - "lib/core/network/**"
#         - "lib/core/storage/**"
#         - "lib/core/validation/**"
#         - "lib/shared/services/**"
#     
#     # Migration progress tracking - error level for migrated files
#     migration_progress_tracker:
#       severity: error
#       exclude:
#         # Allow in transition files
#         - "lib/core/utils/pattern_adapters.dart"
#     
#     # Fold method detection for Either pattern usage
#     fold_method_detected:
#       severity: info
#       exclude:
#         # Allow in adapter files and legitimate fold usage
#         - "lib/core/utils/pattern_adapters.dart"
#         - "**/*_test.dart"