targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
          include:
            - test/**
      build_runner:
        options:
          delete_conflicting_outputs: true
