# Codemagic CI/CD Configuration for EduLift Mobile
# iOS builds enabled with AltStore PAL (no Apple Developer Program needed)
# Android builds handled by GitHub Actions

# NOTE: AltStore PAL distribution
# - AltStore PAL: Free alternative distribution in EU
# - No code signing required (--no-codesign)
# - Firebase App Distribution for .ipa hosting
# - GitHub Pages for AltStore PAL source metadata

workflows:
  # iOS Staging Build
  ios-staging:
    name: iOS Staging
    instance_type: mac_mini_m2
    max_build_duration: 60

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - ios/Pods/.lock
        - .dart_tool

    environment:
      groups:
        - firebase # FIREBASE_SERVICE_ACCOUNT_STAGING
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLAVOR: staging
        BUNDLE_ID: "com.edulift.app.staging"
        ALTSTORE_REPO: "jrevillard/my-altstore"
        ALTSTORE_BRANCH: "main"
      # Note: Set GITHUB_TOKEN in Codemagic environment variables
      # Create Personal Access Token at: https://github.com/settings/tokens
      # Required permissions: repo (full control of private repositories)

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-alpha*'
        - pattern: 'v*-beta*'
        - pattern: 'v*-rc*'
      cancel_previous_builds: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Install dependencies and tools
        script: |
          cd ios && pod install
          # Install jq for JSON parsing and curl for GitHub API
          brew install jq curl

      - name: Configure iOS Deep Links
        script: |
          # Configure iOS deep links from config/DEEP_LINK_BASE_URL
          echo "🔧 Configuring iOS deep links for staging environment"
          ./scripts/configure_ios.sh staging

          # Verify configuration
          echo "📱 iOS Configuration Summary:"
          echo "✅ Info.plist updated with URL schemes"
          if [[ -f "ios/Runner/Runner.entitlements" ]]; then
            echo "✅ Entitlements file created/updated"
            if grep -q "com.apple.developer.associated-domains" ios/Runner/Runner.entitlements; then
              echo "🌐 Universal Links configured"
            else
              echo "📱 Custom URL scheme only (no Universal Links)"
            fi
          else
            echo "📱 Custom URL scheme only (no entitlements needed)"
          fi

      - name: Build iOS IPA for AltStore PAL (staging)
        script: |
          echo "🚀 Building iOS IPA for AltStore PAL (unsigned)"

          # Verify Flutter environment
          echo "📋 Flutter version: $(flutter --version)"
          echo "📋 Working directory: $(pwd)"

          # Verify configuration files exist
          if [[ ! -f "config/staging.json" ]]; then
            echo "❌ Configuration file config/staging.json not found"
            exit 1
          fi
          echo "✅ Configuration file found"

          # Clean previous builds
          echo "🧹 Cleaning previous builds..."
          rm -rf build/ios/ipa/

          # Re-run code generation to ensure latest models
          echo "🔄 Running code generation before build..."
          flutter pub run build_runner build --delete-conflicting-outputs

          # Build unsigned IPA with detailed output
          echo "🔨 Starting Flutter IPA build..."
          flutter build ipa --release \
            --flavor staging \
            --dart-define-from-file=config/staging.json \
            --no-codesign \
            --verbose

          # Check if build command succeeded
          BUILD_EXIT_CODE=$?
          if [[ $BUILD_EXIT_CODE -ne 0 ]]; then
            echo "❌ Flutter build failed with exit code $BUILD_EXIT_CODE"
            exit $BUILD_EXIT_CODE
          fi

          # Get IPA path and info
          echo "🔍 Searching for built IPA..."
          IPA_DIR="build/ios/ipa"
          if [[ ! -d "$IPA_DIR" ]]; then
            echo "❌ IPA directory not found: $IPA_DIR"
            echo "📂 Available directories in build/:"
            find build/ -type d -name "*ios*" 2>/dev/null || echo "No iOS directories found"
            exit 1
          fi

          IPA_PATH=$(find "$IPA_DIR" -name "*.ipa" | head -n 1)
          echo "📦 Built IPA: $IPA_PATH"

          if [[ -f "$IPA_PATH" ]]; then
            echo "✅ IPA built successfully: $(du -h "$IPA_PATH" | cut -f1)"
            echo "📊 IPA details:"
            ls -lh "$IPA_PATH"
            file "$IPA_PATH"
          else
            echo "❌ Failed to build IPA - no .ipa file found"
            echo "📂 Contents of $IPA_DIR:"
            ls -la "$IPA_DIR/" 2>/dev/null || echo "Directory not accessible"
            exit 1
          fi

      - name: Prepare AltStore PAL source update
        script: |
          echo "📱 Preparing AltStore PAL source update for staging"

          # Get build info
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
          VERSION=$(flutter --version | head -n 1 | cut -d' ' -f2)
          BUILD_NUMBER=$(date +%s)
          IPA_SIZE=$(du -h "$IPA_PATH" | cut -f1)

          echo "IPA Path: $IPA_PATH"
          echo "Version: $VERSION"
          echo "Build Number: $BUILD_NUMBER"
          echo "Size: $IPA_SIZE"

          # Create temp directory for AltStore files
          mkdir -p altstore_temp
          cd altstore_temp

          # Clone AltStore repository with authentication
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "🔑 Using GitHub token for authentication"
            git clone https://$GITHUB_TOKEN@github.com/$ALTSTORE_REPO.git .
          else
            echo "⚠️  GITHUB_TOKEN not set, using public clone (may fail for private repos)"
            git clone https://github.com/$ALTSTORE_REPO.git .
          fi
          git checkout $ALTSTORE_BRANCH

          # Construct Firebase App Distribution URL
          # Firebase App Distribution URLs follow this format:
          FIREBASE_URL="https://appdistribution.firebase.google.com/1:390712570284:ios:11ab124204e6c10c054a09"

          echo "Using Firebase URL: $FIREBASE_URL"

          # Update app JSON files
          ./scripts/update-altstore.sh staging "$VERSION" "$BUILD_NUMBER" "$FIREBASE_URL" "$IPA_SIZE"

          echo "✅ AltStore PAL source files updated"

      - name: Commit and push AltStore PAL source updates
        script: |
          cd altstore_temp

          # Configure git
          git config --global user.name "Codemagic CI"
          git config --global user.email "ci@codemagic.io"

          # Add and commit changes
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci(staging): update AltStore PAL source for v$VERSION-$BUILD_NUMBER

            - Version: $VERSION
            - Build: $BUILD_NUMBER
            - Size: $IPA_SIZE
            - Environment: staging"

            # Configure push URL with token for authentication
            if [[ -n "$GITHUB_TOKEN" ]]; then
              git remote set-url origin https://$GITHUB_TOKEN@github.com/$ALTSTORE_REPO.git
            fi

            # Push changes
            git push origin $ALTSTORE_BRANCH
            echo "✅ AltStore PAL source updates pushed to GitHub"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - altstore_temp/**

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_STAGING
        ios:
          app_id: 1:390712570284:ios:11ab124204e6c10c054a09
          groups:
            - staging-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true

  # iOS Production Build
  ios-production:
    name: iOS Production
    instance_type: mac_mini_m2
    max_build_duration: 60

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - ios/Pods/.lock
        - .dart_tool

    environment:
      groups:
        - firebase
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLAVOR: production
        BUNDLE_ID: "com.edulift.app"
        ALTSTORE_REPO: "jrevillard/my-altstore"
        ALTSTORE_BRANCH: "main"
      # Note: Set GITHUB_TOKEN in Codemagic environment variables
      # Create Personal Access Token at: https://github.com/settings/tokens
      # Required permissions: repo (full control of private repositories)

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v[0-9]*.[0-9]*.[0-9]*$'
      cancel_previous_builds: false # Don't cancel production builds

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Install dependencies and tools
        script: |
          cd ios && pod install
          # Install jq for JSON parsing and curl for GitHub API
          brew install jq curl

      - name: Configure iOS Deep Links
        script: |
          # Configure iOS deep links from config/DEEP_LINK_BASE_URL
          echo "🔧 Configuring iOS deep links for production environment"
          ./scripts/configure_ios.sh production

          # Verify configuration
          echo "📱 iOS Configuration Summary:"
          echo "✅ Info.plist updated with URL schemes"
          if [[ -f "ios/Runner/Runner.entitlements" ]]; then
            echo "✅ Entitlements file created/updated"
            if grep -q "com.apple.developer.associated-domains" ios/Runner/Runner.entitlements; then
              echo "🌐 Universal Links configured"
            else
              echo "📱 Custom URL scheme only (no Universal Links)"
            fi
          else
            echo "📱 Custom URL scheme only (no entitlements needed)"
          fi

      - name: Build iOS IPA for AltStore PAL (production)
        script: |
          echo "🚀 Building iOS IPA for AltStore PAL (unsigned)"

          # Verify Flutter environment
          echo "📋 Flutter version: $(flutter --version)"
          echo "📋 Working directory: $(pwd)"

          # Verify configuration files exist
          if [[ ! -f "config/production.json" ]]; then
            echo "❌ Configuration file config/production.json not found"
            exit 1
          fi
          echo "✅ Configuration file found"

          # Clean previous builds
          echo "🧹 Cleaning previous builds..."
          rm -rf build/ios/ipa/

          # Re-run code generation to ensure latest models
          echo "🔄 Running code generation before build..."
          flutter pub run build_runner build --delete-conflicting-outputs

          # Build unsigned IPA with detailed output
          echo "🔨 Starting Flutter IPA build..."
          flutter build ipa --release \
            --flavor production \
            --dart-define-from-file=config/production.json \
            --no-codesign \
            --verbose

          # Check if build command succeeded
          BUILD_EXIT_CODE=$?
          if [[ $BUILD_EXIT_CODE -ne 0 ]]; then
            echo "❌ Flutter build failed with exit code $BUILD_EXIT_CODE"
            exit $BUILD_EXIT_CODE
          fi

          # Get IPA path and info
          echo "🔍 Searching for built IPA..."
          IPA_DIR="build/ios/ipa"
          if [[ ! -d "$IPA_DIR" ]]; then
            echo "❌ IPA directory not found: $IPA_DIR"
            echo "📂 Available directories in build/:"
            find build/ -type d -name "*ios*" 2>/dev/null || echo "No iOS directories found"
            exit 1
          fi

          IPA_PATH=$(find "$IPA_DIR" -name "*.ipa" | head -n 1)
          echo "📦 Built IPA: $IPA_PATH"

          if [[ -f "$IPA_PATH" ]]; then
            echo "✅ IPA built successfully: $(du -h "$IPA_PATH" | cut -f1)"
            echo "📊 IPA details:"
            ls -lh "$IPA_PATH"
            file "$IPA_PATH"
          else
            echo "❌ Failed to build IPA - no .ipa file found"
            echo "📂 Contents of $IPA_DIR:"
            ls -la "$IPA_DIR/" 2>/dev/null || echo "Directory not accessible"
            exit 1
          fi

      - name: Prepare AltStore PAL source update
        script: |
          echo "📱 Preparing AltStore PAL source update for production"

          # Get build info
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
          VERSION=$(flutter --version | head -n 1 | cut -d' ' -f2)
          BUILD_NUMBER=$(date +%s)
          IPA_SIZE=$(du -h "$IPA_PATH" | cut -f1)

          echo "IPA Path: $IPA_PATH"
          echo "Version: $VERSION"
          echo "Build Number: $BUILD_NUMBER"
          echo "Size: $IPA_SIZE"

          # Create temp directory for AltStore files
          mkdir -p altstore_temp
          cd altstore_temp

          # Clone AltStore repository with authentication
          if [[ -n "$GITHUB_TOKEN" ]]; then
            echo "🔑 Using GitHub token for authentication"
            git clone https://$GITHUB_TOKEN@github.com/$ALTSTORE_REPO.git .
          else
            echo "⚠️  GITHUB_TOKEN not set, using public clone (may fail for private repos)"
            git clone https://github.com/$ALTSTORE_REPO.git .
          fi
          git checkout $ALTSTORE_BRANCH

          # Construct Firebase App Distribution URL
          # Firebase App Distribution URLs follow this format:
          FIREBASE_URL="https://appdistribution.firebase.google.com/1:928262951410:ios:139da35e9a165907779b6b"

          echo "Using Firebase URL: $FIREBASE_URL"

          # Update app JSON files
          ./scripts/update-altstore.sh production "$VERSION" "$BUILD_NUMBER" "$FIREBASE_URL" "$IPA_SIZE"

          echo "✅ AltStore PAL source files updated"

      - name: Commit and push AltStore PAL source updates
        script: |
          cd altstore_temp

          # Configure git
          git config --global user.name "Codemagic CI"
          git config --global user.email "ci@codemagic.io"

          # Add and commit changes
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci(production): update AltStore PAL source for v$VERSION-$BUILD_NUMBER

            - Version: $VERSION
            - Build: $BUILD_NUMBER
            - Size: $IPA_SIZE
            - Environment: production"

            # Configure push URL with token for authentication
            if [[ -n "$GITHUB_TOKEN" ]]; then
              git remote set-url origin https://$GITHUB_TOKEN@github.com/$ALTSTORE_REPO.git
            fi

            # Push changes
            git push origin $ALTSTORE_BRANCH
            echo "✅ AltStore PAL source updates pushed to GitHub"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - altstore_temp/**

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_PROD
        ios:
          app_id: 1:928262951410:ios:139da35e9a165907779b6b
          groups:
            - production-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true