# Codemagic CI/CD Configuration for EduLift Mobile
# iOS builds DISABLED - requires Apple Developer Program ($99/year)
# Android builds handled by GitHub Actions

# NOTE: iOS distribution requires Apple Developer Program
# - Ad-hoc distribution: $99/year + device UDID registration
# - TestFlight: $99/year (recommended for testing)
# - App Store: $99/year

workflows:
  # iOS Staging Build (DISABLED - requires Apple Developer Program)
  # Re-enable when Apple Developer account is available
  #
  # To enable: Uncomment the entire section below and update with your
  # Apple Developer credentials
  #
  # ios-staging:
  #   name: iOS Staging
  #   instance_type: mac_mini_m2
  #   max_build_duration: 60
  #
  #   environment:
  #     groups:
  #       - firebase # FIREBASE_SERVICE_ACCOUNT_STAGING
  #     flutter: stable
  #     xcode: latest
  #     cocoapods: default
  #     ios_signing:
  #       distribution_type: ad_hoc
  #       bundle_identifier: com.edulift.app.staging
  #     vars:
  #       FLAVOR: staging
  #       BUNDLE_ID: "com.edulift.app.staging"
  #
  #   triggering:
  #     events:
  #       - tag
  #     tag_patterns:
  #       - pattern: 'v*-alpha*'
  #       - pattern: 'v*-beta*'
  #       - pattern: 'v*-rc*'
  #     cancel_previous_builds: true
  #
  #   scripts:
  #     - name: Get Flutter packages
  #       script: |
  #         flutter pub get
  #
  #     - name: Run code generation
  #       script: |
  #         flutter pub run build_runner build --delete-conflicting-outputs
  #
  #     - name: Install dependencies and tools
  #       script: |
  #         cd ios && pod install
  #         # Install jq for JSON parsing
  #         brew install jq
  #
  #     - name: Configure iOS Deep Links
  #       script: |
  #         # Configure iOS deep links from config/DEEP_LINK_BASE_URL
  #         # This script automatically:
  #         # - Reads DEEP_LINK_BASE_URL from config/staging.json
  #         # - Updates Info.plist with URL schemes
  #         # - Creates/updates Runner.entitlements with Associated Domains
  #         echo "🔧 Configuring iOS deep links for staging environment"
  #         ./scripts/configure_ios.sh staging
  #
  #         # Verify configuration
  #         echo "📱 iOS Configuration Summary:"
  #         echo "✅ Info.plist updated with URL schemes"
  #         if [[ -f "ios/Runner/Runner.entitlements" ]]; then
  #           echo "✅ Entitlements file created/updated"
  #           if grep -q "com.apple.developer.associated-domains" ios/Runner/Runner.entitlements; then
  #             echo "🌐 Universal Links configured"
  #           else
  #             echo "📱 Custom URL scheme only (no Universal Links)"
  #           fi
  #         else
  #           echo "📱 Custom URL scheme only (no entitlements needed)"
  #         fi
  #
  #     - name: Set up code signing settings for iOS
  #       script: |
  #         xcode-project use-profiles --bundle-id="$BUNDLE_ID" --profile-type="APP_STORE"
  #
  #     - name: Build iOS IPA (staging)
  #       script: |
  #         flutter build ipa --release \
  #           --flavor staging \
  #           --dart-define-from-file=config/staging.json \
  #           --export-options-plist=$HOME/export_options.plist
  #
  #   artifacts:
  #     - build/ios/ipa/*.ipa
  #     - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
  #
  #   publishing:
  #     firebase:
  #       firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_STAGING
  #       ios:
  #         app_id: 1:390712570284:ios:11ab124204e6c10c054a09
  #         groups:
  #           - staging-team
  #
  #     email:
  #       recipients:
  #         - jerome.revillard@wanadoo.fr
  #       notify:
  #         success: true
  #         failure: true

  # iOS Production Build (DISABLED - requires Apple Developer Program)
  # ios-production:
  #   name: iOS Production
  #   instance_type: mac_mini_m2
  #   max_build_duration: 60
  #
  #   environment:
  #     groups:
  #       - firebase
  #     flutter: stable
  #     xcode: latest
  #     cocoapods: default
  #     ios_signing:
  #       distribution_type: ad_hoc
  #       bundle_identifier: com.edulift.app
  #     vars:
  #       FLAVOR: production
  #       BUNDLE_ID: "com.edulift.app"
  #
  #   triggering:
  #     events:
  #       - tag
  #     tag_patterns:
  #       - pattern: 'v[0-9]*.[0-9]*.[0-9]*'
  #     cancel_previous_builds: false # Don't cancel production builds
  #
  #   scripts:
  #     - name: Get Flutter packages
  #       script: |
  #         flutter pub get
  #
  #     - name: Run code generation
  #       script: |
  #         flutter pub run build_runner build --delete-conflicting-outputs
  #
  #     - name: Install dependencies and tools
  #       script: |
  #         cd ios && pod install
  #         # Install jq for JSON parsing
  #         brew install jq
  #
  #     - name: Configure iOS Deep Links
  #       script: |
  #         # Configure iOS deep links from config/DEEP_LINK_BASE_URL
  #         # This script automatically:
  #         # - Reads DEEP_LINK_BASE_URL from config/production.json
  #         # - Updates Info.plist with URL schemes
  #         # - Creates/updates Runner.entitlements with Associated Domains
  #         echo "🔧 Configuring iOS deep links for production environment"
  #         ./scripts/configure_ios.sh production
  #
  #         # Verify configuration
  #         echo "📱 iOS Configuration Summary:"
  #         echo "✅ Info.plist updated with URL schemes"
  #         if [[ -f "ios/Runner/Runner.entitlements" ]]; then
  #           echo "✅ Entitlements file created/updated"
  #           if grep -q "com.apple.developer.associated-domains" ios/Runner/Runner.entitlements; then
  #             echo "🌐 Universal Links configured"
  #           else
  #             echo "📱 Custom URL scheme only (no Universal Links)"
  #           fi
  #         else
  #           echo "📱 Custom URL scheme only (no entitlements needed)"
  #         fi
  #
  #     - name: Set up code signing settings for iOS
  #       script: |
  #         xcode-project use-profiles --bundle_id="$BUNDLE_ID" --profile-type="APP_STORE"
  #
  #     - name: Build iOS IPA (production)
  #       script: |
  #         flutter build ipa --release \
  #           --flavor production \
  #           --dart-define-from-file=config/production.json \
  #           --export-options-plist=$HOME/export_options.plist
  #
  #   artifacts:
  #     - build/ios/ipa/*.ipa
  #     - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
  #
  #   publishing:
  #     firebase:
  #       firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_PROD
  #       ios:
  #         app_id: 1:928262951410:ios:139da35e9a165907779b6b
  #         groups:
  #           - production-team
  #
  #     email:
  #       recipients:
  #         - jerome.revillard@wanadoo.fr
  #       notify:
  #         success: true
  #         failure: true