# Codemagic CI/CD Configuration for EduLift Mobile
# iOS builds enabled with AltStore PAL (no Apple Developer Program needed)
# Android builds handled by GitHub Actions

# NOTE: AltStore PAL distribution
# - AltStore PAL: Free alternative distribution in EU
# - No code signing required (--no-codesign)
# - GitHub Releases for .ipa hosting
# - GitHub Pages for AltStore PAL source metadata

definitions:
  scripts:
    - &get-packages
      name: Get Flutter packages
      script: |
        flutter pub get

    - &code-generation
      name: Run code generation
      script: |
        flutter pub run build_runner build --delete-conflicting-outputs

    - &install-tools
      name: Install dependencies and tools
      script: |
        cd ios && pod install
        # Install jq for JSON parsing and curl for GitHub API
        brew install jq curl

    - &configure-ios
      name: Configure iOS Deep Links
      script: |
        # Configure iOS deep links from config/DEEP_LINK_BASE_URL
        echo "🔧 Configuring iOS deep links for $FLAVOR environment"
        ./scripts/configure_ios.sh $FLAVOR

        # Verify configuration
        echo "📱 iOS Configuration Summary:"
        echo "✅ Info.plist updated with URL schemes"
        if [[ -f "ios/Runner/Runner.entitlements" ]]; then
          echo "✅ Entitlements file created/updated"
          if grep -q "com.apple.developer.associated-domains" ios/Runner/Runner.entitlements; then
            echo "🌐 Universal Links configured"
          else
            echo "📱 Custom URL scheme only (no Universal Links)"
          fi
        else
          echo "📱 Custom URL scheme only (no entitlements needed)"
        fi

    - &build-ios
      name: Build iOS IPA
      script: |
        echo "🚀 Building iOS IPA with xcodebuild approach"

        # Verify Flutter environment
        echo "📋 Flutter version: $(flutter --version)"
        echo "📋 Working directory: $(pwd)"

        # Clean previous builds
        echo "🧹 Cleaning previous builds..."
        rm -rf ios/build/

        # Run the build script
        echo "🔧 Running iOS build script..."
        if ./scripts/build_unsigned_ios.sh $FLAVOR; then
          echo "✅ Build completed successfully"
        else
          echo "❌ Build failed"
          exit 1
        fi

        # Find IPA from build location
        echo "🔍 Looking for IPA: ios/build/ipa/edulift-$FLAVOR.ipa"
        echo "🔍 FLAVOR value: $FLAVOR"
        echo "🔍 Available IPA files:"
        find ios/build -name "*.ipa" 2>/dev/null || echo "No IPA files found"

        IPA_PATH="ios/build/ipa/edulift-$FLAVOR.ipa"

        if [[ -f "$IPA_PATH" ]]; then
          echo "✅ IPA found at build location: $IPA_PATH"
          echo "✅ IPA ready!"
          echo "📊 IPA details:"
          ls -lh "$IPA_PATH"
          file "$IPA_PATH"
          echo "📦 Size: $(du -h "$IPA_PATH" | cut -f1)"
        else
          echo "❌ IPA not found at expected location"
          echo "🔍 Available files:"
          find ios/build -name "*.ipa" 2>/dev/null || echo "No IPA files found"
          exit 1
        fi

    - &upload-github
      name: Upload IPA to GitHub Release
      script: |
        echo "📦 Uploading IPA to GitHub Release"

        # Verify GitHub token access first
        echo "🔍 Verifying GitHub token access..."
        if ! curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/user > /dev/null; then
          echo "❌ GitHub token is invalid or lacks permissions"
          echo "Please ensure your token has 'repo' scope (Classic) or 'Contents: Read and write' (Fine-grained)"
          exit 1
        fi
        echo "✅ GitHub token is valid"

        # Get build info and commit info
        IPA_PATH="ios/build/ipa/edulift-$FLAVOR.ipa"
        if [[ ! -f "$IPA_PATH" ]]; then
          echo "❌ IPA not found at expected location: $IPA_PATH"
          exit 1
        fi
        BUILD_NUMBER=$(date +%s)
        IPA_SIZE=$(du -h "$IPA_PATH" | cut -f1)

        # Get current commit SHA for the release
        COMMIT_SHA=$(git rev-parse HEAD)

        echo "IPA Path: $IPA_PATH"
        echo "Build Number: $BUILD_NUMBER"
        echo "Size: $IPA_SIZE"
        echo "Commit SHA: $COMMIT_SHA"

        # Extract version from pubspec.yaml (managed by Android CD)
        if [[ ! -f "pubspec.yaml" ]]; then
          echo "❌ pubspec.yaml not found!"
          echo "This is a critical error - the app version must be defined in pubspec.yaml"
          exit 1
        fi

        # Extract current version from pubspec.yaml (Android CD updates this)
        FULL_VERSION=$(grep "^version:" pubspec.yaml | cut -d':' -f2 | xargs)

        # Parse version and build number (format: "1.0.0+123")
        VERSION=$(echo "$FULL_VERSION" | cut -d'+' -f1)
        # Use iOS timestamp build number instead of Android run number to avoid conflicts
        IOS_BUILD_NUMBER=$(date +%s)
        echo "📌 Found pubspec.yaml version: $FULL_VERSION"
        echo "📌 Using iOS build number: $IOS_BUILD_NUMBER (different from Android run number to avoid conflicts)"

        BUILD_NUMBER=$IOS_BUILD_NUMBER

        echo "Version: $VERSION (from pubspec.yaml: $FULL_VERSION)"
        echo "Build Number: $BUILD_NUMBER (iOS timestamp)"

        # Create release using GitHub API with tag if on tagged build, otherwise commit SHA
        if [[ -n "${GITHUB_REF_NAME}" && "${GITHUB_REF_TYPE}" == "tag" ]]; then
          # Tagged build: use tag-based release
          RELEASE_TAG="${GITHUB_REF_NAME}"
          echo "🏷️  Using tag-based release: $RELEASE_TAG"
        else
          # Commit-based build: use commit SHA for precision
          RELEASE_TAG="v$VERSION-$COMMIT_SHA"
          echo "🔗 Using commit-based release: $RELEASE_TAG"
        fi
        RELEASE_NAME="EduLift iOS $FLAVOR $RELEASE_TAG"

        # Set prerelease based on flavor
        IS_PRERELEASE=true
        if [[ "$FLAVOR" == "production" ]]; then
          IS_PRERELEASE=false
        fi

        RELEASE_DATA=$(cat << EOF
        {
          "tag_name": "$RELEASE_TAG",
          "target_commitish": "$COMMIT_SHA",
          "name": "$RELEASE_NAME",
          "body": "EduLift iOS $FLAVOR build\n\n- Version: $VERSION\n- Build: $BUILD_NUMBER\n- Size: $IPA_SIZE\n- Environment: $FLAVOR\n- Commit: $COMMIT_SHA",
          "draft": true,
          "prerelease": $IS_PRERELEASE
        }
        EOF
        )

        # Create release
        echo "🏷️  Creating release $RELEASE_TAG..."
        API_URL="https://api.github.com/repos/jrevillard/edulift-mobile/releases"

        echo "🌐 API URL: $API_URL"
        echo "📝 Release data preview:"
        echo "$RELEASE_DATA" | head -5
        echo "   ..."

        # Make the API call
        echo "🚀 Making API call..."
        RELEASE_RESPONSE=$(curl -s -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$API_URL" \
          -d "$RELEASE_DATA")

        # Extract upload URL from response
        UPLOAD_URL=$(echo "$RELEASE_RESPONSE" | jq -r '.upload_url' | sed 's/{?name,label}//' 2>/dev/null || echo "")
        RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id' 2>/dev/null || echo "")
        ERROR_MESSAGE=$(echo "$RELEASE_RESPONSE" | jq -r '.message' 2>/dev/null || echo "")

        if [[ "$UPLOAD_URL" == "null" || "$UPLOAD_URL" == "" ]]; then
          echo ""
          echo "❌ Failed to create release"
          echo "🐛 Debugging info:"
          echo "   - HTTP Status: $HTTP_STATUS"
          echo "   - Error Message: $ERROR_MESSAGE"
          echo "   - JSON Response: $JSON_RESPONSE"
          echo "   - Full Response: $RELEASE_RESPONSE"
          echo ""
          echo "🔧 Try running the test script:"
          echo "   export GITHUB_TOKEN=your_token"
          echo "   ./scripts/test-github-api.sh"
          exit 1
        fi

        echo "✅ Release created: $RELEASE_ID"
        echo "📤 Upload URL: $UPLOAD_URL"

        # Upload IPA
        echo "📤 Uploading IPA to release..."
        IPA_FILENAME="edulift-$FLAVOR.ipa"
        UPLOAD_RESPONSE=$(curl -s -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "$UPLOAD_URL?name=$IPA_FILENAME" \
          --data-binary @"$IPA_PATH")

        DOWNLOAD_URL=$(echo "$UPLOAD_RESPONSE" | jq -r '.browser_download_url')

        if [[ "$DOWNLOAD_URL" == "null" || "$DOWNLOAD_URL" == "" ]]; then
          echo "❌ Failed to upload IPA"
          echo "Response: $UPLOAD_RESPONSE"
          exit 1
        fi

        echo "✅ IPA uploaded successfully!"
        echo "🔗 Temporary Download URL: $DOWNLOAD_URL"

        # Publish the release (make it non-draft)
        echo "📢 Publishing release..."
        PUBLISH_RESPONSE=$(curl -s -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/jrevillard/edulift-mobile/releases/$RELEASE_ID \
          -d '{"draft": false}')

        echo "📡 Publish response: $PUBLISH_RESPONSE"

        # Get the correct download URL after publishing
        echo "🔄 Getting final download URL..."
        FINAL_DOWNLOAD_URL="https://github.com/jrevillard/edulift-mobile/releases/download/$RELEASE_TAG/$IPA_FILENAME"
        echo "🔗 Final Download URL: $FINAL_DOWNLOAD_URL"

        # Update the download URL variable for next step
        DOWNLOAD_URL="$FINAL_DOWNLOAD_URL"
        echo "✅ Updated to proper download URL: $DOWNLOAD_URL"

        # Save download URL to temp file for next script (Codemagic doesn't have GITHUB_ENV)
        echo "$DOWNLOAD_URL" > /tmp/download_url.txt

    - &update-altstore
      name: Prepare AltStore PAL source update
      script: |
        echo "📱 Preparing AltStore PAL source update for $FLAVOR"

        # Load download URL from previous script (Codemagic environment sharing)
        if [[ -f "/tmp/download_url.txt" ]]; then
          DOWNLOAD_URL=$(cat /tmp/download_url.txt)
          echo "✅ Loaded download URL from previous step: $DOWNLOAD_URL"
        else
          echo "❌ Download URL file not found - previous step must have failed"
          exit 1
        fi

        if [[ -z "$DOWNLOAD_URL" ]]; then
          echo "❌ Download URL is empty - previous step must have failed"
          exit 1
        fi
        VERSION=$(flutter --version | head -n 1 | cut -d' ' -f2)
        BUILD_NUMBER=$(date +%s)
        IPA_SIZE=$(du -h "ios/build/ipa/edulift-$FLAVOR.ipa" | cut -f1)

        echo "Download URL: $DOWNLOAD_URL"
        echo "Version: $VERSION"
        echo "Build Number: $BUILD_NUMBER"
        echo "Size: $IPA_SIZE"

        # Create temp directory for AltStore files
        mkdir -p altstore_temp
        cd altstore_temp

        # Clone AltStore repository with authentication
        if [[ -n "$GITHUB_TOKEN" ]]; then
          echo "🔑 Using GitHub token for authentication"
          git clone https://$GITHUB_TOKEN@github.com/$ALTSTORE_REPO.git .
        else
          echo "⚠️  GITHUB_TOKEN not set, using public clone (may fail for private repos)"
          git clone https://github.com/$ALTSTORE_REPO.git .
        fi
        git checkout $ALTSTORE_BRANCH

        echo "Using GitHub Release URL: $DOWNLOAD_URL"

        # Generate AltStore PAL JSON files directly
        echo "🔄 Updating AltStore PAL source files for $FLAVOR environment"
        echo "   - Version: $VERSION"
        echo "   - Build Number: $BUILD_NUMBER"
        echo "   - IPA Size: $IPA_SIZE"
        echo "   - Download URL: $DOWNLOAD_URL"

        # Create directory structure for AltStore files
        mkdir -p apps
        mkdir -p icons

        # Generate app-specific JSON file
        APP_JSON="apps/${FLAVOR}.json"
        cat > "$APP_JSON" << EOF
        {
          "name": "EduLift",
          "bundleIdentifier": "com.edulift.app${FLAVOR:+:.staging}",
          "version": "$VERSION",
          "versionDate": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "localizedDescription": "Version $VERSION - Build $BUILD_NUMBER",
          "downloadURL": "$DOWNLOAD_URL",
          "size": $IPA_SIZE,
          "iconURL": "https://raw.githubusercontent.com/jrevillard/edulift-mobile/main/docs/edulift-icon.png",
          "tintColor": "#1976d2"
        }
        EOF

        echo "✅ Generated $APP_JSON:"
        echo "   - Name: EduLift ${FLAVOR}"
        echo "   - Bundle ID: com.edulift.app${FLAVOR:+:.staging}"
        echo "   - Download URL: $DOWNLOAD_URL"
        echo "   - Size: $IPA_SIZE"

        echo "✅ AltStore PAL source files updated"

    - &commit-altstore
      name: Commit and push AltStore PAL source updates
      script: |
        cd altstore_temp

        # Configure git
        git config --global user.name "Codemagic CI"
        git config --global user.email "ci@codemagic.io"

        # Add and commit changes
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "ci($FLAVOR): update AltStore PAL source for v$VERSION-$BUILD_NUMBER

          - Version: $VERSION
          - Build: $BUILD_NUMBER
          - Size: $IPA_SIZE
          - Environment: $FLAVOR"

          # Configure push URL with token for authentication
          if [[ -n "$GITHUB_TOKEN" ]]; then
            git remote set-url origin https://$GITHUB_TOKEN@github.com/$ALTSTORE_REPO.git
          fi

          # Push changes
          git push origin $ALTSTORE_BRANCH
          echo "✅ AltStore PAL source updates pushed to GitHub"
        fi

workflows:
  # iOS Staging Build
  ios-staging:
    name: iOS Staging
    instance_type: mac_mini_m2
    max_build_duration: 60

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - ios/Pods/.lock
        - .dart_tool

    environment:
      groups:
        - firebase # FIREBASE_SERVICE_ACCOUNT_STAGING
      # Versions from .github/ci-versions.env - Use Codemagic UI variables to override
      flutter: 3.38.2
      xcode: 16.4
      cocoapods: default
      vars:
        FLAVOR: staging
        BUNDLE_ID: "com.edulift.app.staging"
        ALTSTORE_REPO: "jrevillard/my-altstore"
        ALTSTORE_BRANCH: "main"
        GITHUB_REF_NAME: "${{ github.ref_name }}"
        GITHUB_REF_TYPE: "${{ github.ref_type }}"
      # Note: Set GITHUB_TOKEN in Codemagic environment variables
      # Create Personal Access Token at: https://github.com/settings/tokens
      # Required permissions: repo (full control of private repositories)

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-alpha*'
        - pattern: 'v*-beta*'
        - pattern: 'v*-rc*'
      cancel_previous_builds: true

    scripts:
      - *get-packages
      - *code-generation
      - *install-tools
      - &update-version
        name: Update version from tag
        script: |
          # Update pubspec.yaml version from tag (same logic as Android CD)
          if [[ -n "${GITHUB_REF_NAME}" && "${GITHUB_REF_TYPE}" == "tag" && "${GITHUB_REF_NAME}" =~ ^v.* ]]; then
            echo "🏷️  Updating pubspec.yaml from tag: ${GITHUB_REF_NAME}"

            # Remove 'v' prefix
            TAG_NAME="${GITHUB_REF_NAME}"
            VERSION="${TAG_NAME#v}"

            # Extract base version (remove pre-release suffix)
            BASE_VERSION=$(echo "$VERSION" | sed -E 's/(-alpha|-beta|-rc).*//')

            # Use timestamp for iOS build number
            IOS_BUILD_NUMBER=$(date +%s)

            echo "📌 Tag: $TAG_NAME"
            echo "📌 Extracted version: $BASE_VERSION"
            echo "📌 iOS build number: $IOS_BUILD_NUMBER"

            # Update pubspec.yaml with new version
            sed -i '' "s/^version: .*/version: $BASE_VERSION+$IOS_BUILD_NUMBER/" pubspec.yaml

            echo "✅ Updated pubspec.yaml:"
            grep "^version:" pubspec.yaml
          else
            echo "ℹ️  Not a version tag, keeping existing pubspec.yaml version"
          fi
      - *configure-ios
      - *build-ios
      - *upload-github
      - *update-altstore
      - *commit-altstore

    artifacts:
      - ios/build/ipa/*.ipa
      - altstore_temp/**

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_STAGING
        ios:
          app_id: 1:390712570284:ios:11ab124204e6c10c054a09
          groups:
            - staging-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true

  # iOS Production Build
  ios-production:
    name: iOS Production
    instance_type: mac_mini_m2
    max_build_duration: 60

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
        - ios/Pods/.lock
        - .dart_tool

    environment:
      groups:
        - firebase
      # Versions from .github/ci-versions.env - Use Codemagic UI variables to override
      flutter: 3.38.2
      xcode: 16.4
      cocoapods: default
      vars:
        FLAVOR: production
        BUNDLE_ID: "com.edulift.app"
        ALTSTORE_REPO: "jrevillard/my-altstore"
        ALTSTORE_BRANCH: "main"
        GITHUB_REF_NAME: "${ github.ref_name }}"
        GITHUB_REF_TYPE: "${ github.ref_type }"
      # Note: Set GITHUB_TOKEN in Codemagic environment variables
      # Create Personal Access Token at: https://github.com/settings/tokens
      # Required permissions: repo (full control of private repositories)

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v[0-9]*.[0-9]*.[0-9]*$'
      cancel_previous_builds: false # Don't cancel production builds

    scripts:
      - *get-packages
      - *code-generation
      - *install-tools
      - *update-version
      - *configure-ios
      - *build-ios
      - *upload-github
      - *update-altstore
      - *commit-altstore

    artifacts:
      - ios/build/ipa/*.ipa
      - altstore_temp/**

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_PROD
        ios:
          app_id: 1:928262951410:ios:139da35e9a165907779b6b
          groups:
            - production-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true