# Codemagic CI/CD Configuration for EduLift Mobile
# iOS builds only (staging and production)
# Android builds handled by GitHub Actions
# Uses Codemagic automatic code signing (no Apple Developer account required)

workflows:
  # iOS Staging Build (pre-release tags: v*-rc.*, v*-beta.*, v*-alpha.*)
  ios-staging:
    name: iOS Staging
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - firebase # FIREBASE_SERVICE_ACCOUNT_STAGING
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.edulift.app.staging
      vars:
        FLAVOR: staging
        BUNDLE_ID: "com.edulift.app.staging"

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-alpha*'
        - pattern: 'v*-beta*'
        - pattern: 'v*-rc*'
      cancel_previous_builds: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Extract version from tag and update pubspec.yaml
        script: |
          # CM_TAG contains the tag name, ex: v0.1.0-alpha1
          # Remove 'v' prefix
          VERSION="${CM_TAG#v}"

          # Extract base version (remove -alpha, -beta, etc.)
          BASE_VERSION=$(echo "$VERSION" | sed -E 's/(-alpha|-beta|-rc).*//')

          # Use Codemagic build number
          VERSION_CODE="$CM_BUILD_NUMBER"

          echo "📌 Tag: $CM_TAG"
          echo "📌 Extracted version: $BASE_VERSION"
          echo "📌 Version code: $VERSION_CODE"

          # Update pubspec.yaml
          sed -i "" "s/^version: .*/version: $BASE_VERSION+$VERSION_CODE/" pubspec.yaml

          # Verify the change
          echo "✅ Updated pubspec.yaml:"
          grep "^version:" pubspec.yaml

      - name: Set up code signing
        script: |
          keychain initialize

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Set up code signing settings for iOS
        script: |
          xcode-project use-profiles --bundle-id="$BUNDLE_ID" --profile-type="APP_STORE"

      - name: Build iOS IPA (staging)
        script: |
          flutter build ipa --release \
            --flavor staging \
            --dart-define-from-file=config/staging.json \
            --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_STAGING
        ios:
          app_id: 1:390712570284:ios:11ab124204e6c10c054a09
          groups:
            - staging-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true

  # iOS Production Build (production tags: v*.*.*)
  ios-production:
    name: iOS Production
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - firebase
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.edulift.app
      vars:
        FLAVOR: production
        BUNDLE_ID: "com.edulift.app"

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v[0-9]*.[0-9]*.[0-9]*'
      cancel_previous_builds: false # Don't cancel production builds

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Extract version from tag and update pubspec.yaml
        script: |
          # CM_TAG contains the tag name, ex: v1.0.0
          # Remove 'v' prefix
          VERSION="${CM_TAG#v}"

          # Extract base version (remove -alpha, -beta, etc.) - shouldn't have any for production
          BASE_VERSION=$(echo "$VERSION" | sed -E 's/(-alpha|-beta|-rc).*//')

          # Use Codemagic build number
          VERSION_CODE="$CM_BUILD_NUMBER"

          echo "📌 Tag: $CM_TAG"
          echo "📌 Extracted version: $BASE_VERSION"
          echo "📌 Version code: $VERSION_CODE"

          # Update pubspec.yaml
          sed -i "" "s/^version: .*/version: $BASE_VERSION+$VERSION_CODE/" pubspec.yaml

          # Verify the change
          echo "✅ Updated pubspec.yaml:"
          grep "^version:" pubspec.yaml

      - name: Set up code signing
        script: |
          keychain initialize

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Set up code signing settings for iOS
        script: |
          xcode-project use-profiles --bundle-id="$BUNDLE_ID" --profile-type="APP_STORE"

      - name: Build iOS IPA (production)
        script: |
          flutter build ipa --release \
            --flavor production \
            --dart-define-from-file=config/production.json \
            --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_PROD
        ios:
          app_id: 1:928262951410:ios:139da35e9a165907779b6b
          groups:
            - production-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true
