# Codemagic CI/CD Configuration for EduLift Mobile
# iOS builds only (staging and production)
# Android builds handled by GitHub Actions
# Uses Codemagic automatic code signing (no Apple Developer account required)

workflows:
  # iOS Staging Build (pre-release tags: v*-rc.*, v*-beta.*, v*-alpha.*)
  ios-staging:
    name: iOS Staging
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - firebase # FIREBASE_SERVICE_ACCOUNT_STAGING
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.edulift.app.staging
      vars:
        FLAVOR: staging
        BUNDLE_ID: "com.edulift.app.staging"

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*-rc.*'
        - pattern: 'v*-beta.*'
        - pattern: 'v*-alpha.*'
      cancel_previous_builds: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Set up code signing
        script: |
          keychain initialize

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Set up automatic code signing
        script: |
          xcode-project use-profiles

      - name: Set build number
        script: |
          export BUILD_NUMBER=$(date +%s)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      - name: Build iOS IPA (staging)
        script: |
          flutter build ipa --release \
            --flavor staging \
            --dart-define-from-file=config/staging.json \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_STAGING
        ios:
          app_id: 1:390712570284:ios:11ab124204e6c10c054a09
          groups:
            - staging-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true

  # iOS Production Build (production tags: v*.*.*)
  ios-production:
    name: iOS Production
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - firebase
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.edulift.app
      vars:
        FLAVOR: production
        BUNDLE_ID: "com.edulift.app"

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v[0-9]+.[0-9]+.[0-9]+$'
      cancel_previous_builds: false # Don't cancel production builds

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Run code generation
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Set up code signing
        script: |
          keychain initialize

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Set up automatic code signing
        script: |
          xcode-project use-profiles

      - name: Set build number
        script: |
          export BUILD_NUMBER=$(date +%s)
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV

      - name: Build iOS IPA (production)
        script: |
          flutter build ipa --release \
            --flavor production \
            --dart-define-from-file=config/production.json \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_PROD
        ios:
          app_id: 1:928262951410:ios:139da35e9a165907779b6b
          groups:
            - production-team

      email:
        recipients:
          - jerome.revillard@wanadoo.fr
        notify:
          success: true
          failure: true
