// Mocks generated by Mockito 5.4.6 from annotations
// in edulift/test/unit/features/schedule/domain/usecases/assign_vehicle_to_slot_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:edulift/core/domain/entities/schedule.dart' as _i6;
import 'package:edulift/core/errors/failures.dart' as _i7;
import 'package:edulift/core/utils/result.dart' as _i5;
import 'package:edulift/features/family/domain/entities/child_assignment.dart'
    as _i9;
import 'package:edulift/features/schedule/domain/repositories/schedule_repository.dart'
    as _i3;
import 'package:edulift/features/schedule/domain/services/schedule_datetime_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScheduleDateTimeValidationResult_1 extends _i1.SmartFake
    implements _i2.ScheduleDateTimeValidationResult {
  _FakeScheduleDateTimeValidationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [GroupScheduleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupScheduleRepository extends _i1.Mock
    implements _i3.GroupScheduleRepository {
  MockGroupScheduleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>>
  getWeeklySchedule(String? groupId, String? week) =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklySchedule, [groupId, week]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#getWeeklySchedule, [groupId, week]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>> getScheduleConfig(
    String? groupId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleConfig, [groupId]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>
                  >(this, Invocation.method(#getScheduleConfig, [groupId])),
                ),
          )
          as _i4.Future<_i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>> upsertScheduleSlot(
    String? groupId,
    String? day,
    String? time,
    String? week,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertScheduleSlot, [groupId, day, time, week]),
            returnValue:
                _i4.Future<_i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>>.value(
                  _i8.dummyValue<_i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>>(
                    this,
                    Invocation.method(#upsertScheduleSlot, [
                      groupId,
                      day,
                      time,
                      week,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>>
  assignVehicleToSlot(
    String? groupId,
    String? day,
    String? time,
    String? week,
    String? vehicleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignVehicleToSlot, [
              groupId,
              day,
              time,
              week,
              vehicleId,
            ]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#assignVehicleToSlot, [
                      groupId,
                      day,
                      time,
                      week,
                      vehicleId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiFailure>> removeVehicleFromSlot(
    String? groupId,
    String? slotId,
    String? vehicleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeVehicleFromSlot, [
              groupId,
              slotId,
              vehicleId,
            ]),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiFailure>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiFailure>>(
                this,
                Invocation.method(#removeVehicleFromSlot, [
                  groupId,
                  slotId,
                  vehicleId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiFailure>> removeVehicleFromSlotWithWeek(
    String? groupId,
    String? slotId,
    String? vehicleId,
    String? week,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeVehicleFromSlotWithWeek, [
              groupId,
              slotId,
              vehicleId,
              week,
            ]),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiFailure>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiFailure>>(
                this,
                Invocation.method(#removeVehicleFromSlotWithWeek, [
                  groupId,
                  slotId,
                  vehicleId,
                  week,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>>
  assignChildrenToVehicle(
    String? groupId,
    String? slotId,
    String? vehicleAssignmentId,
    List<String>? childIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignChildrenToVehicle, [
              groupId,
              slotId,
              vehicleAssignmentId,
              childIds,
            ]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#assignChildrenToVehicle, [
                      groupId,
                      slotId,
                      vehicleAssignmentId,
                      childIds,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiFailure>> removeChildFromVehicle(
    String? groupId,
    String? slotId,
    String? vehicleAssignmentId,
    String? childAssignmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeChildFromVehicle, [
              groupId,
              slotId,
              vehicleAssignmentId,
              childAssignmentId,
            ]),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiFailure>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiFailure>>(
                this,
                Invocation.method(#removeChildFromVehicle, [
                  groupId,
                  slotId,
                  vehicleAssignmentId,
                  childAssignmentId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i9.ChildAssignment, _i7.ApiFailure>>
  updateChildAssignmentStatus(
    String? groupId,
    String? slotId,
    String? vehicleAssignmentId,
    String? childAssignmentId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateChildAssignmentStatus, [
              groupId,
              slotId,
              vehicleAssignmentId,
              childAssignmentId,
              status,
            ]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i9.ChildAssignment, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i9.ChildAssignment, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#updateChildAssignmentStatus, [
                      groupId,
                      slotId,
                      vehicleAssignmentId,
                      childAssignmentId,
                      status,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i9.ChildAssignment, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>>
  updateSeatOverride(
    String? groupId,
    String? vehicleAssignmentId,
    int? seatOverride,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSeatOverride, [
              groupId,
              vehicleAssignmentId,
              seatOverride,
            ]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#updateSeatOverride, [
                      groupId,
                      vehicleAssignmentId,
                      seatOverride,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.VehicleAssignment, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<List<_i6.ScheduleConflict>, _i7.ApiFailure>>
  checkScheduleConflicts(
    String? groupId,
    String? vehicleId,
    String? week,
    String? day,
    String? time,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkScheduleConflicts, [
              groupId,
              vehicleId,
              week,
              day,
              time,
            ]),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i6.ScheduleConflict>, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i6.ScheduleConflict>, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#checkScheduleConflicts, [
                      groupId,
                      vehicleId,
                      week,
                      day,
                      time,
                    ]),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Result<List<_i6.ScheduleConflict>, _i7.ApiFailure>
          >);

  @override
  _i4.Future<_i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>>
  updateScheduleConfig(String? groupId, _i6.ScheduleConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateScheduleConfig, [groupId, config]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#updateScheduleConfig, [groupId, config]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>>
  resetScheduleConfig(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#resetScheduleConfig, [groupId]),
            returnValue:
                _i4.Future<
                  _i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>
                  >(this, Invocation.method(#resetScheduleConfig, [groupId])),
                ),
          )
          as _i4.Future<_i5.Result<_i6.ScheduleConfig, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiFailure>> copyWeeklySchedule(
    String? groupId,
    String? sourceWeek,
    String? targetWeek,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#copyWeeklySchedule, [
              groupId,
              sourceWeek,
              targetWeek,
            ]),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiFailure>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiFailure>>(
                this,
                Invocation.method(#copyWeeklySchedule, [
                  groupId,
                  sourceWeek,
                  targetWeek,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiFailure>> clearWeeklySchedule(
    String? groupId,
    String? week,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#clearWeeklySchedule, [groupId, week]),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiFailure>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiFailure>>(
                this,
                Invocation.method(#clearWeeklySchedule, [groupId, week]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>, _i7.ApiFailure>>
  getScheduleStatistics(String? groupId, String? week) =>
      (super.noSuchMethod(
            Invocation.method(#getScheduleStatistics, [groupId, week]),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<Map<String, dynamic>, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(#getScheduleStatistics, [groupId, week]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>, _i7.ApiFailure>>);

  @override
  _i4.Stream<_i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>>
  listenToScheduleUpdates(String? groupId, String? week) =>
      (super.noSuchMethod(
            Invocation.method(#listenToScheduleUpdates, [groupId, week]),
            returnValue:
                _i4.Stream<
                  _i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>
                >.empty(),
          )
          as _i4.Stream<_i5.Result<_i6.ScheduleSlot, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<void, _i7.ApiFailure>> sendTypingIndicator(
    String? groupId,
    String? userId,
    String? action,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendTypingIndicator, [
              groupId,
              userId,
              action,
              metadata,
            ]),
            returnValue: _i4.Future<_i5.Result<void, _i7.ApiFailure>>.value(
              _i8.dummyValue<_i5.Result<void, _i7.ApiFailure>>(
                this,
                Invocation.method(#sendTypingIndicator, [
                  groupId,
                  userId,
                  action,
                  metadata,
                ]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void, _i7.ApiFailure>>);

  @override
  _i4.Stream<_i5.Result<Map<String, dynamic>, _i7.ApiFailure>>
  listenToTypingIndicators(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#listenToTypingIndicators, [groupId]),
            returnValue:
                _i4.Stream<
                  _i5.Result<Map<String, dynamic>, _i7.ApiFailure>
                >.empty(),
          )
          as _i4.Stream<_i5.Result<Map<String, dynamic>, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>>
  getGroupSchedules(String? groupId, {DateTime? fromDate, DateTime? toDate}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getGroupSchedules,
              [groupId],
              {#fromDate: fromDate, #toDate: toDate},
            ),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(
                      #getGroupSchedules,
                      [groupId],
                      {#fromDate: fromDate, #toDate: toDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.ScheduleSlot>, _i7.ApiFailure>>);

  @override
  _i4.Future<_i5.Result<Map<String, dynamic>, _i7.ApiFailure>>
  optimizeGroupSchedule(
    String? groupId,
    String? week, {
    String? criteria = 'efficiency',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #optimizeGroupSchedule,
              [groupId, week],
              {#criteria: criteria},
            ),
            returnValue:
                _i4.Future<
                  _i5.Result<Map<String, dynamic>, _i7.ApiFailure>
                >.value(
                  _i8.dummyValue<
                    _i5.Result<Map<String, dynamic>, _i7.ApiFailure>
                  >(
                    this,
                    Invocation.method(
                      #optimizeGroupSchedule,
                      [groupId, week],
                      {#criteria: criteria},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<Map<String, dynamic>, _i7.ApiFailure>>);
}

/// A class which mocks [ScheduleDateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScheduleDateTimeService extends _i1.Mock
    implements _i2.ScheduleDateTimeService {
  MockScheduleDateTimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime? calculateWeekStartDate(String? week) =>
      (super.noSuchMethod(Invocation.method(#calculateWeekStartDate, [week]))
          as DateTime?);

  @override
  DateTime? calculateDateTimeFromSlot(
    String? day,
    String? time,
    String? week,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDateTimeFromSlot, [day, time, week]),
          )
          as DateTime?);

  @override
  DateTime calculateWeekEndDate(DateTime? weekStart) =>
      (super.noSuchMethod(
            Invocation.method(#calculateWeekEndDate, [weekStart]),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#calculateWeekEndDate, [weekStart]),
            ),
          )
          as DateTime);

  @override
  bool isPastDate(DateTime? dateTime, {String? userTimezone}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isPastDate,
              [dateTime],
              {#userTimezone: userTimezone},
            ),
            returnValue: false,
          )
          as bool);

  @override
  _i2.ScheduleDateTimeValidationResult validateScheduleDateTime(
    DateTime? dateTime, {
    String? userTimezone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateScheduleDateTime,
              [dateTime],
              {#userTimezone: userTimezone},
            ),
            returnValue: _FakeScheduleDateTimeValidationResult_1(
              this,
              Invocation.method(
                #validateScheduleDateTime,
                [dateTime],
                {#userTimezone: userTimezone},
              ),
            ),
          )
          as _i2.ScheduleDateTimeValidationResult);
}
