name: Setup Flutter Environment
description: 'Setup Java, Flutter, and get dependencies'
author: 'EduLift Team'
inputs:
  flutter-version:
    description: 'Flutter version to use (must match workflow FLUTTER_VERSION)'
    required: true
  java-version:
    description: 'Java version to use (must match workflow JAVA_VERSION)'
    required: true
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
        cache: true
        cache-key: 'flutter-stable-${{ inputs.flutter-version }}-${{ inputs.cache-key-suffix }}'

    - name: Get dependencies
      shell: bash
      run: flutter pub get

    - name: Verify Flutter installation
      shell: bash
      run: flutter --version