name: Setup Flutter Environment
description: 'Setup Java, Flutter, and get dependencies'
author: 'EduLift Team'
inputs:
  flutter-version:
    description: 'Flutter version to use'
    required: false
    default: '3.19.6'
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      shell: bash
      run: flutter pub get

    - name: Verify Flutter installation
      shell: bash
      run: flutter --version