// Mocks generated by Mockito 5.4.6 from annotations
// in edulift/test/unit/core/services/token_refresh_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dio/dio.dart' as _i7;
import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i10;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:edulift/core/errors/failures.dart' as _i13;
import 'package:edulift/core/network/models/common/api_response_wrapper.dart'
    as _i9;
import 'package:edulift/core/network/network_error_handler.dart' as _i15;
import 'package:edulift/core/storage/auth_local_datasource.dart' as _i11;
import 'package:edulift/core/utils/result.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFuture_6<T1> extends _i1.SmartFake implements _i8.Future<T1> {
  _FakeFuture_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeApiResponse_7<T1> extends _i1.SmartFake
    implements _i9.ApiResponse<T1> {
  _FakeApiResponse_7(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_0(this, Invocation.getter(#options)),
      ) as _i2.BaseOptions);

  @override
  _i3.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_1(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i3.HttpClientAdapter);

  @override
  _i4.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_2(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i4.Transformer);

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_3(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(#options, _options),
        returnValueForMissingStub: null,
      );

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(#transformer, _transformer),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(#close, [], {#force: force}),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {#data: data, #options: options, #cancelToken: cancelToken},
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {#data: data, #options: options, #cancelToken: cancelToken},
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i10.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [urlPath, savePath],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue: _i8.Future<_i6.Response<dynamic>>.value(
          _FakeResponse_4<dynamic>(
            this,
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<dynamic>>);

  @override
  _i8.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i10.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [uri, savePath],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue: _i8.Future<_i6.Response<dynamic>>.value(
          _FakeResponse_4<dynamic>(
            this,
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<dynamic>>);

  @override
  _i8.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i10.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i10.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(#fetch, [requestOptions]),
        returnValue: _i8.Future<_i6.Response<T>>.value(
          _FakeResponse_4<T>(
            this,
            Invocation.method(#fetch, [requestOptions]),
          ),
        ),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i3.HttpClientAdapter? httpClientAdapter,
    _i4.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#clone, [], {
          #options: options,
          #interceptors: interceptors,
          #httpClientAdapter: httpClientAdapter,
          #transformer: transformer,
        }),
        returnValue: _FakeDio_5(
          this,
          Invocation.method(#clone, [], {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          }),
        ),
      ) as _i7.Dio);
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i11.AuthLocalDatasource {
  MockAuthLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> saveToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(#saveToken, [token]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#saveToken, [token]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<String?, _i13.ApiFailure>> getToken() =>
      (super.noSuchMethod(
        Invocation.method(#getToken, []),
        returnValue: _i8.Future<_i12.Result<String?, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<String?, _i13.ApiFailure>>(
            this,
            Invocation.method(#getToken, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<String?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> storeTokens({
    required String? accessToken,
    required String? refreshToken,
    required DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#storeTokens, [], {
          #accessToken: accessToken,
          #refreshToken: refreshToken,
          #expiresAt: expiresAt,
        }),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#storeTokens, [], {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #expiresAt: expiresAt,
            }),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<String?, _i13.ApiFailure>> getRefreshToken() =>
      (super.noSuchMethod(
        Invocation.method(#getRefreshToken, []),
        returnValue: _i8.Future<_i12.Result<String?, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<String?, _i13.ApiFailure>>(
            this,
            Invocation.method(#getRefreshToken, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<String?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<DateTime?, _i13.ApiFailure>> getTokenExpiry() =>
      (super.noSuchMethod(
        Invocation.method(#getTokenExpiry, []),
        returnValue: _i8.Future<_i12.Result<DateTime?, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<DateTime?, _i13.ApiFailure>>(
            this,
            Invocation.method(#getTokenExpiry, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<DateTime?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> clearTokens() =>
      (super.noSuchMethod(
        Invocation.method(#clearTokens, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#clearTokens, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> saveUserProfile(
    _i11.AuthUserProfile? profile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#saveUserProfile, [profile]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#saveUserProfile, [profile]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<_i11.AuthUserProfile?, _i13.ApiFailure>>
      getUserProfile() => (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i8.Future<
                _i12.Result<_i11.AuthUserProfile?, _i13.ApiFailure>>.value(
              _i14.dummyValue<
                      _i12.Result<_i11.AuthUserProfile?, _i13.ApiFailure>>(
                  this, Invocation.method(#getUserProfile, [])),
            ),
          ) as _i8.Future<_i12.Result<_i11.AuthUserProfile?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> saveAuthState(
    _i11.AuthState? state,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#saveAuthState, [state]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#saveAuthState, [state]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<_i11.AuthState?, _i13.ApiFailure>> getAuthState() =>
      (super.noSuchMethod(
        Invocation.method(#getAuthState, []),
        returnValue:
            _i8.Future<_i12.Result<_i11.AuthState?, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<_i11.AuthState?, _i13.ApiFailure>>(
              this, Invocation.method(#getAuthState, [])),
        ),
      ) as _i8.Future<_i12.Result<_i11.AuthState?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> clearSession() =>
      (super.noSuchMethod(
        Invocation.method(#clearSession, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#clearSession, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> cleanupExpiredTokens() =>
      (super.noSuchMethod(
        Invocation.method(#cleanupExpiredTokens, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#cleanupExpiredTokens, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<bool, _i13.ApiFailure>> isStorageHealthy() =>
      (super.noSuchMethod(
        Invocation.method(#isStorageHealthy, []),
        returnValue: _i8.Future<_i12.Result<bool, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<bool, _i13.ApiFailure>>(
            this,
            Invocation.method(#isStorageHealthy, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<bool, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> storeToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(#storeToken, [token]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#storeToken, [token]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> clearToken() =>
      (super.noSuchMethod(
        Invocation.method(#clearToken, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#clearToken, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> storeUserData(dynamic user) =>
      (super.noSuchMethod(
        Invocation.method(#storeUserData, [user]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#storeUserData, [user]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> storePKCEVerifier(
    String? codeVerifier,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#storePKCEVerifier, [codeVerifier]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#storePKCEVerifier, [codeVerifier]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<String?, _i13.ApiFailure>> getPKCEVerifier() =>
      (super.noSuchMethod(
        Invocation.method(#getPKCEVerifier, []),
        returnValue: _i8.Future<_i12.Result<String?, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<String?, _i13.ApiFailure>>(
            this,
            Invocation.method(#getPKCEVerifier, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<String?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> clearPKCEVerifier() =>
      (super.noSuchMethod(
        Invocation.method(#clearPKCEVerifier, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#clearPKCEVerifier, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> storeMagicLinkEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#storeMagicLinkEmail, [email]),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#storeMagicLinkEmail, [email]),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<String?, _i13.ApiFailure>> getMagicLinkEmail() =>
      (super.noSuchMethod(
        Invocation.method(#getMagicLinkEmail, []),
        returnValue: _i8.Future<_i12.Result<String?, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<String?, _i13.ApiFailure>>(
            this,
            Invocation.method(#getMagicLinkEmail, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<String?, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> clearMagicLinkEmail() =>
      (super.noSuchMethod(
        Invocation.method(#clearMagicLinkEmail, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#clearMagicLinkEmail, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);

  @override
  _i8.Future<_i12.Result<void, _i13.ApiFailure>> clearUserData() =>
      (super.noSuchMethod(
        Invocation.method(#clearUserData, []),
        returnValue: _i8.Future<_i12.Result<void, _i13.ApiFailure>>.value(
          _i14.dummyValue<_i12.Result<void, _i13.ApiFailure>>(
            this,
            Invocation.method(#clearUserData, []),
          ),
        ),
      ) as _i8.Future<_i12.Result<void, _i13.ApiFailure>>);
}

/// A class which mocks [NetworkErrorHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkErrorHandler extends _i1.Mock
    implements _i15.NetworkErrorHandler {
  MockNetworkErrorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<T> executeWithRetry<T>(
    _i8.Future<T> Function()? operation, {
    required String? operationName,
    String? serviceName,
    _i15.RetryConfig? config = const _i15.RetryConfig(),
    Duration? timeout,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeWithRetry,
          [operation],
          {
            #operationName: operationName,
            #serviceName: serviceName,
            #config: config,
            #timeout: timeout,
            #context: context,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #executeWithRetry,
                  [operation],
                  {
                    #operationName: operationName,
                    #serviceName: serviceName,
                    #config: config,
                    #timeout: timeout,
                    #context: context,
                  },
                ),
              ),
              (T v) => _i8.Future<T>.value(v),
            ) ??
            _FakeFuture_6<T>(
              this,
              Invocation.method(
                #executeWithRetry,
                [operation],
                {
                  #operationName: operationName,
                  #serviceName: serviceName,
                  #config: config,
                  #timeout: timeout,
                  #context: context,
                },
              ),
            ),
      ) as _i8.Future<T>);

  @override
  _i8.Future<_i9.ApiResponse<T>> executeApiCall<T>(
    _i8.Future<T> Function()? apiCall, {
    required String? operationName,
    String? serviceName,
    _i15.RetryConfig? config = const _i15.RetryConfig(),
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeApiCall,
          [apiCall],
          {
            #operationName: operationName,
            #serviceName: serviceName,
            #config: config,
            #context: context,
          },
        ),
        returnValue: _i8.Future<_i9.ApiResponse<T>>.value(
          _FakeApiResponse_7<T>(
            this,
            Invocation.method(
              #executeApiCall,
              [apiCall],
              {
                #operationName: operationName,
                #serviceName: serviceName,
                #config: config,
                #context: context,
              },
            ),
          ),
        ),
      ) as _i8.Future<_i9.ApiResponse<T>>);

  @override
  Map<String, dynamic> getCircuitStatus() => (super.noSuchMethod(
        Invocation.method(#getCircuitStatus, []),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void resetAllCircuitBreakers() => super.noSuchMethod(
        Invocation.method(#resetAllCircuitBreakers, []),
        returnValueForMissingStub: null,
      );

  @override
  void resetCircuitBreaker(String? serviceName) => super.noSuchMethod(
        Invocation.method(#resetCircuitBreaker, [serviceName]),
        returnValueForMissingStub: null,
      );
}
