// Mocks generated by Mockito 5.4.6 from annotations
// in edulift/test/presentation/features/schedule/widgets/mobile/enhanced_slot_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:edulift/core/domain/entities/user.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccessibilityPreferences_1 extends _i1.SmartFake
    implements _i2.AccessibilityPreferences {
  _FakeAccessibilityPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_2 extends _i1.SmartFake implements _i2.User {
  _FakeUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  DateTime get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#createdAt)),
          )
          as DateTime);

  @override
  DateTime get updatedAt =>
      (super.noSuchMethod(
            Invocation.getter(#updatedAt),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#updatedAt)),
          )
          as DateTime);

  @override
  _i2.UserRole get role =>
      (super.noSuchMethod(
            Invocation.getter(#role),
            returnValue: _i2.UserRole.user,
          )
          as _i2.UserRole);

  @override
  bool get hasCompletedOnboarding =>
      (super.noSuchMethod(
            Invocation.getter(#hasCompletedOnboarding),
            returnValue: false,
          )
          as bool);

  @override
  _i2.AccessibilityPreferences get accessibilityPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#accessibilityPreferences),
            returnValue: _FakeAccessibilityPreferences_1(
              this,
              Invocation.getter(#accessibilityPreferences),
            ),
          )
          as _i2.AccessibilityPreferences);

  @override
  bool get isBiometricEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isBiometricEnabled),
            returnValue: false,
          )
          as bool);

  @override
  String get initials =>
      (super.noSuchMethod(
            Invocation.getter(#initials),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#initials),
            ),
          )
          as String);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  bool get isSetupComplete =>
      (super.noSuchMethod(
            Invocation.getter(#isSetupComplete),
            returnValue: false,
          )
          as bool);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);

  @override
  _i2.User copyWith({
    String? id,
    String? email,
    String? name,
    DateTime? createdAt,
    DateTime? updatedAt,
    Object? preferredLanguage = const Object(),
    Object? timezone = const Object(),
    _i2.UserRole? role,
    bool? hasCompletedOnboarding,
    _i2.AccessibilityPreferences? accessibilityPreferences,
    bool? isBiometricEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #email: email,
              #name: name,
              #createdAt: createdAt,
              #updatedAt: updatedAt,
              #preferredLanguage: preferredLanguage,
              #timezone: timezone,
              #role: role,
              #hasCompletedOnboarding: hasCompletedOnboarding,
              #accessibilityPreferences: accessibilityPreferences,
              #isBiometricEnabled: isBiometricEnabled,
            }),
            returnValue: _FakeUser_2(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #email: email,
                #name: name,
                #createdAt: createdAt,
                #updatedAt: updatedAt,
                #preferredLanguage: preferredLanguage,
                #timezone: timezone,
                #role: role,
                #hasCompletedOnboarding: hasCompletedOnboarding,
                #accessibilityPreferences: accessibilityPreferences,
                #isBiometricEnabled: isBiometricEnabled,
              }),
            ),
          )
          as _i2.User);
}
